rvm:
- 2.4.2
sudo: false
branches:
  only:
    - master
bundler_args: "--without development:production:intercode1_import"
cache:
  bundler: true
  directories:
    - node_modules
    - public/packs-test
  yarn: true
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
jobs:
  include:
    - name: Ruby
      language: ruby
      if: env(LANGUAGE) = ruby
      script:
      - cp config/database.yml.ci config/database.yml
      - bin/rake db:create db:migrate RAILS_ENV=test
      - bin/rake test
      - ./cc-test-reporter format-coverage --output coverage/codeclimate.ruby.json
    - name: Javascript
      language: javascript
      if: env(LANGUAGE) = javascript
      script:
      - nvm install
      - npm install --global yarn
      - yarn install
      - yarn run test
      - ./cc-test-reporter format-coverage --output coverage/codeclimate.js.json
notifications:
  slack:
    secure: Ca/xHuvVik0EfevEAmMuLH+Ybd2yj7FuYsSmxJ/4dyxisuKg+tUvnJEZxnrU/QtHOdSyIh3ZAA4gVHd8PALuJ0HYOjotogqCZaQ0ZYTB7pKVvxc8u8YK7aY3P58guib7SrU3iRXsvjaV5xOflaBY4Ng1TQrkc8TCU4i8xZhWxWc=
env:
  global:
    - CC_TEST_REPORTER_ID=2ec5e525d523a261ed68d45eb18865e8ea7a5b32751290cabde2d44f39e78cce
  matrix:
    - DATABASE=sqlite LANGUAGE=ruby
    - DATABASE=mysql LANGUAGE=ruby
    - DATABASE=postgresql LANGUAGE=ruby
    - LANGUAGE=javascript
addons:
  code_climate:
    repo_token: 2ec5e525d523a261ed68d45eb18865e8ea7a5b32751290cabde2d44f39e78cce
after_success:
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json
  - ./cc-test-reporter upload-coverage
