version: '3.4'
services:
  web:
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      DEVELOPMENT_DATABASE_URL: mysql2://root:mysql@mysql/intercode_development
      TEST_DATABASE_URL: mysql2://root:mysql@mysql/intercode_test
  mysql:
    image: mysql:5.7
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata:
