version: '3.4'
services:
  web:
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:10.4
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
