version: '3.4'
services:
  web:
    image: neinteractiveliterature/intercode:test-${TRAVIS_COMMIT}
    build:
      context: .
      dockerfile: Dockerfile.web
      cache_from:
        - neinteractiveliterature/intercode:build-latest
        - neinteractiveliterature/intercode:build-${TRAVIS_PULL_REQUEST_BRANCH}
      target: test
  shoryuken:
    image: neinteractiveliterature/intercode:test-${TRAVIS_COMMIT}
