version: '3.4'
services:
  web:
    image: neinteractiveliterature/intercode:${TRAVIS_COMMIT}
    build:
      context: .
      dockerfile: Dockerfile.web
      cache_from:
        - neinteractiveliterature/intercode:build-latest
        - neinteractiveliterature/intercode:build-${TRAVIS_PULL_REQUEST_BRANCH}
    ports:
      - "3000:3000"
