version: '3'
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - postgres
      - redis
  postgres:
    image: postgres:9.6
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
    expose:
      - "6379"
volumes:
  pgdata:
