version: '3.4'
services:
  web:
    build:
      context: .
      cache_from:
        - neinteractiveliterature/intercode:latest
        - neinteractiveliterature/intercode:${TRAVIS_PULL_REQUEST_BRANCH}
    ports:
      - "3000:3000"
    links:
      - postgres
      - mysql
  mysql:
    image: mysql:5.7
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - mysqldata:/var/lib/mysql
  postgres:
    image: postgres:10.4
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  mysqldata:
