version: '3.4'
services:
  web:
    image: neinteractiveliterature/intercode:test-${TRAVIS_COMMIT}
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - neinteractiveliterature/intercode:build-latest
        - neinteractiveliterature/intercode:build-${TRAVIS_PULL_REQUEST_BRANCH}
      target: test
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      DEVELOPMENT_DATABASE_URL: postgresql://postgres:postgres@postgres/intercode_development
      TEST_DATABASE_URL: postgresql://postgres:postgres@postgres/intercode_test
  shoryuken:
    image: neinteractiveliterature/intercode:test-${TRAVIS_COMMIT}
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      DEVELOPMENT_DATABASE_URL: postgresql://postgres:postgres@postgres/intercode_development
      TEST_DATABASE_URL: postgresql://postgres:postgres@postgres/intercode_test
  postgres:
    image: postgres:10.4
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
