version: '3.4'
services:
  web:
    image: neinteractiveliterature/intercode:${TRAVIS_COMMIT}
    build:
      context: .
      cache_from:
        - neinteractiveliterature/intercode:latest
        - neinteractiveliterature/intercode:${TRAVIS_PULL_REQUEST_BRANCH}
    ports:
      - "3000:3000"
