version: 2.1

jobs:
  check-and-build-only:
    environment:
      ASSETS_HOST: assets.neilhosting.net

    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set BRANCH_TAG
          command: |
            export BRANCH_TAG=$(echo ${CIRCLE_BRANCH:-master} | sed 's/[^[:alnum:]]/-/g') ; echo $BRANCH_TAG
      - run:
          name: Pull docker images
          command: |
            sh test/docker-pull.sh
      - run:
          name: docker build --target build
          command: |
            docker build \
              -f Dockerfile \
              --network=host \
              --target build \
              --build-arg ASSETS_HOST="$ASSETS_HOST" \
              --cache-from neinteractiveliterature/intercode:${BRANCH_TAG} \
              --cache-from neinteractiveliterature/intercode:latest \
              --cache-from neinteractiveliterature/intercode:build-production-${BRANCH_TAG} \
              --cache-from neinteractiveliterature/intercode:build-production-master \
              -t neinteractiveliterature/intercode:local-build \
              .
      - run:
          name: docker build --target build-production
          command: |
            docker build \
              -f Dockerfile \
              --target build-production \
              --network=host \
              --build-arg ASSETS_HOST="$ASSETS_HOST" \
              --cache-from neinteractiveliterature/intercode:${BRANCH_TAG} \
              --cache-from neinteractiveliterature/intercode:latest \
              --cache-from neinteractiveliterature/intercode:local-build \
              --cache-from neinteractiveliterature/intercode:build-production-${BRANCH_TAG} \
              --cache-from neinteractiveliterature/intercode:build-production-master \
              -t neinteractiveliterature/intercode:build-production-${CIRCLE_SHA1} \
              .
      - run:
          name: tag build-production
          command: docker tag neinteractiveliterature/intercode:build-production-${CIRCLE_SHA1} neinteractiveliterature/intercode:build-production-${BRANCH_TAG}
      - run:
          name: docker build --target production
          command: |
            docker build \
              -f Dockerfile \
              --target production \
              --build-arg ASSETS_HOST="$ASSETS_HOST" \
              --cache-from neinteractiveliterature/intercode:${BRANCH_TAG} \
              --cache-from neinteractiveliterature/intercode:latest \
              --cache-from neinteractiveliterature/intercode:local-build \
              --cache-from neinteractiveliterature/intercode:build-production-${CIRCLE_SHA1} \
              -t neinteractiveliterature/intercode:${CIRCLE_SHA1} \
              .
      - run:
          name: docker build --target test
          command: |
            docker build \
              -f Dockerfile \
              --target test \
              --build-arg ASSETS_HOST="$ASSETS_HOST" \
              --cache-from neinteractiveliterature/intercode:${BRANCH_TAG} \
              --cache-from neinteractiveliterature/intercode:test-${BRANCH_TAG} \
              --cache-from neinteractiveliterature/intercode:local-build \
              --cache-from neinteractiveliterature/intercode:build-production-${CIRCLE_SHA1} \
              --cache-from neinteractiveliterature/intercode:${CIRCLE_SHA1} \
              -t neinteractiveliterature/intercode:test-${CIRCLE_SHA1} \
              .
  test:
    docker:
      - image: docker:stable-git
    steps:
      - run:
          name: Install Docker Compose
          command: |
            apk add --no-cache curl
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Run tests
          command: |
            docker-compose -f docker-compose.test.yml run \
            -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
            -e CI=$CI -e CIRCLE_SHA1=$CIRCLE_SHA1 \
            -e CIRCLE_BRANCH=$CIRCLE_BRANCH \
            -e CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM
            -e CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID \
            -e GIT_COMMITTED_AT=$(git log -1 --pretty=format:%ct) \
            web \
            test/travis-complete.sh

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  build:
    jobs:
      - check-and-build-only
      - test:
          requires:
            - check-and-build-only

