version: 2.1

jobs:
  check-and-build-only:
    environment:
      ASSETS_HOST: assets.neilhosting.net

    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            export BRANCH_TAG=$(echo ${CIRCLE_BRANCH:-master} | sed 's/[^[:alnum:]]/-/g') ; echo $BRANCH_TAG
      - run:
          command: |
            bash test/docker-pull.sh
      - run:
          command: |
            docker build
              -f Dockerfile
              --network=host
              --target build
              --build-arg ASSETS_HOST="$ASSETS_HOST"
              --cache-from neinteractiveliterature/intercode:${BRANCH_TAG}
              --cache-from neinteractiveliterature/intercode:latest
              --cache-from neinteractiveliterature/intercode:build-production-${BRANCH_TAG}
              --cache-from neinteractiveliterature/intercode:build-production-master
              -t neinteractiveliterature/intercode:local-build
                .

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  build:
    jobs:
      - check-and-build-only
