version: 2.1

jobs:
  check-and-build-only:
    docker:
      - image: docker-18.09.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            docker build .

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  build:
    jobs:
      - check-and-build-only
