development:
  adapter: postgresql
  database: intercode_development
  user: postgres

test:
  adapter: postgresql
  database: intercode_test
  user: postgres

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
