# This database config file is used for CI environments that set the database using
# the DATABASE environment variable.

development:
  pool: 5
  timeout: 5000
  url: <%= ENV['DEVELOPMENT_DATABASE_URL'] %>

test:
  pool: 5
  timeout: 5000
  url: <%= ENV['TEST_DATABASE_URL'] %>

production:
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>
