steps:
  - name: "gcr.io/cloud-builders/git"
    args: ['clone', 'https://github.com/neinteractiveliterature/intercode']
  - name: "gcr.io/cloud-builders/docker"
    args: [
        "build",
        '--cache-from', 'gcr.io/$PROJECT_ID/intercode:latest',
        "-t", "gcr.io/$PROJECT_ID/intercode:$REVISION_ID",
        "-f", "Dockerfile",
        "."
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "tag",
      "gcr.io/$PROJECT_ID/intercode:$REVISION_ID",
      "gcr.io/$PROJECT_ID/intercode:latest"
    ]
  - name: "gcr.io/cloud-builders/kubectl"
    args: "set image deployment/intercode intercode=intercode:$REVISION_ID"
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
images:
  - "gcr.io/$PROJECT_ID/intercode:$REVISION_ID"
  - "gcr.io/$PROJECT_ID/intercode:latest"
