apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: intercode
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: intercode
    spec:
      containers:
      - name: intercode
        image: neinteractiveliterature/intercode:latest
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        env:
        - name: AWS_REGION
          value: us-east-1
        - name: AWS_S3_BUCKET
          value: intercode2-production
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: intercode-aws-credentials
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: intercode-aws-credentials
              key: aws-secret-access-key
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: intercode-aws-credentials
              key: database-url
        - name: MAILGUN_DOMAIN
          value: interconlarp.org
        - name: MAILGUN_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: intercode-mailgun-credentials
              key: mailgun-private-key
        - name: MAILGUN_PUBLIC_KEY
          value: pubkey-a516538e7b546eb5ca1c25d0cfb90900
        - name: MAILGUN_SMTP_LOGIN
          value: postmaster@interconlarp.org
        - name: MAILGUN_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: intercode-mailgun-credentials
              key: mailgun-smtp-password
        - name: MAILGUN_SMTP_PORT
          value: 587
        - name: MAILGUN_SMTP_SERVER
          value: smtp.mailgun.org
        - name: MALLOC_ARENA_MAX
          value: 2
        - name: RAILS_ENV
          value: production
        command: ["bundle"]
        args: ["exec", "rails", "server", "-p", "3000", "-b", "0.0.0.0"]
        ports:
        - containerPort: 3000
