apiVersion: v1
kind: Service
metadata:
  name: intercode
  labels:
    app: intercode
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: intercode
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
