name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Log into Docker Hub
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DockerHubUsername }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DockerHubPassword }}
      run: echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - name: Log into Github Package Registry
      env:
        GITHUB_PACKAGE_REGISTRY_USERNAME: ${{ secrets.GithubPackageRegistryUsername }}
        GITHUB_PACKAGE_REGISTRY_PASSWORD: ${{ secrets.GithubPackageRegistryPassword }}
      run: echo "$GITHUB_PACKAGE_REGISTRY_PASSWORD" | docker login docker.pkg.github.com -u "$GITHUB_PACKAGE_REGISTRY_USERNAME" --password-stdin
    - name: Pull Docker images for build
      run: docker pull docker.pkg.github.com/${GITHUB_REPOSITORY}/intercode:build-production-master || true
    - name: Build the "local-build" Docker image
      run: docker build . --build-arg ASSETS_HOST=assets.neilhosting.net --cache-from docker.pkg.github.com/${GITHUB_REPOSITORY}/intercode:build-production-master --target build --tag local-build
    - name: Build the "build-production" Docker image
      run: docker build . --build-arg ASSETS_HOST=assets.neilhosting.net --cache-from local-build --cache-from docker.pkg.github.com/${GITHUB_REPOSITORY}/intercode:build-production-master --target build-production --tag local-build-production
    - name: Download container-diff
      run: curl -LO https://storage.googleapis.com/container-diff/latest/container-diff-linux-amd64 && chmod +x container-diff-linux-amd64
    - name: Diff the images
      run: ./container-diff-linux-amd64 diff docker.pkg.github.com/${GITHUB_REPOSITORY}/intercode:build-production-master local-build-production
#     - name: Tag build-production for Github Package Registry
#       run: docker tag local-build-production docker.pkg.github.com/${GITHUB_REPOSITORY}/intercode:build-production-master
#     - name: Push build-production to Github Package Registry
#       run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/intercode:build-production-master
#     - name: Build the "test" Docker image
#       run: docker build . --build-arg ASSETS_HOST=assets.neilhosting.net --cache-from local-build-production --target test --tag local-test
#     - name: Tag the "test" Docker image so Compose will see it (temporary while we're on Travis)
#       run: docker tag local-test neinteractiveliterature/intercode:build-latest
#     - name: Run tests
#       env:
#         CC_TEST_REPORTER_ID: ${{ secrets.CodeClimateTestReporterId }}
#       run: docker-compose -f docker-compose.test.yml run
#         -e GIT_COMMIT_SHA=$GITHUB_SHA -e GIT_BRANCH=$GITHUB_REF
#         -e GIT_COMMITTED_AT=$(git log -1 --pretty=format:%ct)
#         -e CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
#         web
#         test/travis-complete.sh
